/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'blog-post': BlogPost;
    hackathon: Hackathon;
    media: PayloadMedia;
    users: User;
  };
  globals: {
    'about-me': AboutMeData;
    footer: FooterData;
  };
}
export interface BlogPost {
  id: string;
  title: string;
  description: string;
  featuredImage?: string | PayloadMedia;
  showFeaturedImage?: boolean;
  content: {
    [k: string]: unknown;
  }[];
  slug: string;
  postedDate: string;
  enableComments?: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMedia {
  id: string;
  altText?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Hackathon {
  id: string;
  title: string;
  description: string;
  event: string;
  featuredImage?: string | PayloadMedia;
  showFeaturedImage?: boolean;
  content: {
    [k: string]: unknown;
  }[];
  slug: string;
  postedDate: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface AboutMeData {
  id: string;
  image: string | PayloadMedia;
  content: {
    [k: string]: unknown;
  }[];
}
export interface FooterData {
  id: string;
  socialLinks?: {
    ariaLabel?: string;
    url?: string;
    icon?: 'email' | 'facebook' | 'github' | 'instagram' | 'linkedin' | 'reddit' | 'telegram' | 'twitter';
    openInNewTab?: boolean;
    id?: string;
  }[];
  copyrightText?: string;
}
